# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: labelshift

on:
  push:
    branches: [ main dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install labelshift module
      run: |
        pip install .
    - name: Check code with flake8
      run: |
        flake8
    - name: Check whether yapf has been used.
      run: |
        yapf --diff -r tests/
        yapf --diff -r labelshift/
    - name: Check docstring coverage with interrogate
      run: |
        interrogate
    - name: Check types with pytype
      run: |
        pytype
    - name: Test with pytest
      run: |
        pytest
